package com.shoulaxiao.model;

import java.util.Date;

public class EdgeDO {

    private Long id;

    private String startNode;

    private String endNode;

    private Double cosValue;

    private Integer belongGraph;

    private Date createTime;

    private Date updateTime;

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_edge.id
     *
     * @param id the value for data_edge.id
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_edge.start_node
     *
     * @return the value of data_edge.start_node
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public String getStartNode() {
        return startNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_edge.start_node
     *
     * @param startNode the value for data_edge.start_node
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public void setStartNode(String startNode) {
        this.startNode = startNode == null ? null : startNode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_edge.end_node
     *
     * @return the value of data_edge.end_node
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public String getEndNode() {
        return endNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_edge.end_node
     *
     * @param endNode the value for data_edge.end_node
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public void setEndNode(String endNode) {
        this.endNode = endNode == null ? null : endNode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_edge.cos_value
     *
     * @return the value of data_edge.cos_value
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public Double getCosValue() {
        return cosValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_edge.cos_value
     *
     * @param cosValue the value for data_edge.cos_value
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public void setCosValue(Double cosValue) {
        this.cosValue = cosValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_edge.belong_graph
     *
     * @return the value of data_edge.belong_graph
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public Integer getBelongGraph() {
        return belongGraph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_edge.belong_graph
     *
     * @param belongGraph the value for data_edge.belong_graph
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public void setBelongGraph(Integer belongGraph) {
        this.belongGraph = belongGraph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_edge.create_time
     *
     * @return the value of data_edge.create_time
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_edge.create_time
     *
     * @param createTime the value for data_edge.create_time
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_edge.update_time
     *
     * @return the value of data_edge.update_time
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_edge.update_time
     *
     * @param updateTime the value for data_edge.update_time
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}