package com.shoulaxiao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NodeDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    public NodeDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNodeCodeIsNull() {
            addCriterion("node_code is null");
            return (Criteria) this;
        }

        public Criteria andNodeCodeIsNotNull() {
            addCriterion("node_code is not null");
            return (Criteria) this;
        }

        public Criteria andNodeCodeEqualTo(String value) {
            addCriterion("node_code =", value, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andNodeCodeNotEqualTo(String value) {
            addCriterion("node_code <>", value, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andNodeCodeGreaterThan(String value) {
            addCriterion("node_code >", value, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andNodeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("node_code >=", value, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andNodeCodeLessThan(String value) {
            addCriterion("node_code <", value, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andNodeCodeLessThanOrEqualTo(String value) {
            addCriterion("node_code <=", value, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andNodeCodeLike(String value) {
            addCriterion("node_code like", value, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andNodeCodeNotLike(String value) {
            addCriterion("node_code not like", value, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andNodeCodeIn(List<String> values) {
            addCriterion("node_code in", values, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andNodeCodeNotIn(List<String> values) {
            addCriterion("node_code not in", values, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andNodeCodeBetween(String value1, String value2) {
            addCriterion("node_code between", value1, value2, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andNodeCodeNotBetween(String value1, String value2) {
            addCriterion("node_code not between", value1, value2, "nodeCode");
            return (Criteria) this;
        }

        public Criteria andDensityValueIsNull() {
            addCriterion("density_value is null");
            return (Criteria) this;
        }

        public Criteria andDensityValueIsNotNull() {
            addCriterion("density_value is not null");
            return (Criteria) this;
        }

        public Criteria andDensityValueEqualTo(Double value) {
            addCriterion("density_value =", value, "densityValue");
            return (Criteria) this;
        }

        public Criteria andDensityValueNotEqualTo(Double value) {
            addCriterion("density_value <>", value, "densityValue");
            return (Criteria) this;
        }

        public Criteria andDensityValueGreaterThan(Double value) {
            addCriterion("density_value >", value, "densityValue");
            return (Criteria) this;
        }

        public Criteria andDensityValueGreaterThanOrEqualTo(Double value) {
            addCriterion("density_value >=", value, "densityValue");
            return (Criteria) this;
        }

        public Criteria andDensityValueLessThan(Double value) {
            addCriterion("density_value <", value, "densityValue");
            return (Criteria) this;
        }

        public Criteria andDensityValueLessThanOrEqualTo(Double value) {
            addCriterion("density_value <=", value, "densityValue");
            return (Criteria) this;
        }

        public Criteria andDensityValueIn(List<Double> values) {
            addCriterion("density_value in", values, "densityValue");
            return (Criteria) this;
        }

        public Criteria andDensityValueNotIn(List<Double> values) {
            addCriterion("density_value not in", values, "densityValue");
            return (Criteria) this;
        }

        public Criteria andDensityValueBetween(Double value1, Double value2) {
            addCriterion("density_value between", value1, value2, "densityValue");
            return (Criteria) this;
        }

        public Criteria andDensityValueNotBetween(Double value1, Double value2) {
            addCriterion("density_value not between", value1, value2, "densityValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueIsNull() {
            addCriterion("vector_value is null");
            return (Criteria) this;
        }

        public Criteria andVectorValueIsNotNull() {
            addCriterion("vector_value is not null");
            return (Criteria) this;
        }

        public Criteria andVectorValueEqualTo(String value) {
            addCriterion("vector_value =", value, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueNotEqualTo(String value) {
            addCriterion("vector_value <>", value, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueGreaterThan(String value) {
            addCriterion("vector_value >", value, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueGreaterThanOrEqualTo(String value) {
            addCriterion("vector_value >=", value, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueLessThan(String value) {
            addCriterion("vector_value <", value, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueLessThanOrEqualTo(String value) {
            addCriterion("vector_value <=", value, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueLike(String value) {
            addCriterion("vector_value like", value, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueNotLike(String value) {
            addCriterion("vector_value not like", value, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueIn(List<String> values) {
            addCriterion("vector_value in", values, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueNotIn(List<String> values) {
            addCriterion("vector_value not in", values, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueBetween(String value1, String value2) {
            addCriterion("vector_value between", value1, value2, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andVectorValueNotBetween(String value1, String value2) {
            addCriterion("vector_value not between", value1, value2, "vectorValue");
            return (Criteria) this;
        }

        public Criteria andBelongGraphIsNull() {
            addCriterion("belong_graph is null");
            return (Criteria) this;
        }

        public Criteria andBelongGraphIsNotNull() {
            addCriterion("belong_graph is not null");
            return (Criteria) this;
        }

        public Criteria andBelongGraphEqualTo(Integer value) {
            addCriterion("belong_graph =", value, "belongGraph");
            return (Criteria) this;
        }

        public Criteria andBelongGraphNotEqualTo(Integer value) {
            addCriterion("belong_graph <>", value, "belongGraph");
            return (Criteria) this;
        }

        public Criteria andBelongGraphGreaterThan(Integer value) {
            addCriterion("belong_graph >", value, "belongGraph");
            return (Criteria) this;
        }

        public Criteria andBelongGraphGreaterThanOrEqualTo(Integer value) {
            addCriterion("belong_graph >=", value, "belongGraph");
            return (Criteria) this;
        }

        public Criteria andBelongGraphLessThan(Integer value) {
            addCriterion("belong_graph <", value, "belongGraph");
            return (Criteria) this;
        }

        public Criteria andBelongGraphLessThanOrEqualTo(Integer value) {
            addCriterion("belong_graph <=", value, "belongGraph");
            return (Criteria) this;
        }

        public Criteria andBelongGraphIn(List<Integer> values) {
            addCriterion("belong_graph in", values, "belongGraph");
            return (Criteria) this;
        }

        public Criteria andBelongGraphNotIn(List<Integer> values) {
            addCriterion("belong_graph not in", values, "belongGraph");
            return (Criteria) this;
        }

        public Criteria andBelongGraphBetween(Integer value1, Integer value2) {
            addCriterion("belong_graph between", value1, value2, "belongGraph");
            return (Criteria) this;
        }

        public Criteria andBelongGraphNotBetween(Integer value1, Integer value2) {
            addCriterion("belong_graph not between", value1, value2, "belongGraph");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_node
     *
     * @mbggenerated do_not_delete_during_merge Wed May 13 14:15:32 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}