package com.shoulaxiao.dao;

import com.shoulaxiao.model.EdgeDO;

import java.util.List;

public interface EdgeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    int insert(EdgeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    int insertSelective(EdgeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    EdgeDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    int updateByPrimaryKeySelective(EdgeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    int updateByPrimaryKey(EdgeDO record);

    /**
     * 批量插入
     * @param records
     * @return
     */
    int insertByBatch(List<EdgeDO> records);
}