package com.shoulaxiao.dao;

import com.shoulaxiao.model.EdgeDO;
import com.shoulaxiao.model.EdgeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EdgeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    int countByExample(EdgeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    int deleteByExample(EdgeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    int insert(EdgeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    int insertSelective(EdgeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    List<EdgeDO> selectByExample(EdgeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    EdgeDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") EdgeDO record, @Param("example") EdgeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    int updateByExample(@Param("record") EdgeDO record, @Param("example") EdgeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    int updateByPrimaryKeySelective(EdgeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_edge
     *
     * @mbggenerated Wed May 13 14:15:32 CST 2020
     */
    int updateByPrimaryKey(EdgeDO record);

    /**
     * 批量插图
     * @param records
     * @return
     */
    int insertByBatch(List<EdgeDO> records);
}