package com.shoulaxiao.dao;

import com.shoulaxiao.model.NodeDO;

public interface NodeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    int insert(NodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    int insertSelective(NodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    NodeDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    int updateByPrimaryKeySelective(NodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_node
     *
     * @mbggenerated Wed May 13 12:41:20 CST 2020
     */
    int updateByPrimaryKey(NodeDO record);
}